# Generated by Django 4.1.1 on 2023-02-26 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='time_send',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_1',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_2',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_3',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_4',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_5',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_6',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='time_send_days_7',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
