# Generated by Django 4.1.1 on 2023-02-26 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_remove_subscriber_date_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_1',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
    ]
