# Generated by Django 4.1.1 on 2023-02-26 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0003_alter_subscriber_time_send_days_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_2',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_3',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_4',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_5',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_6',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='time_send_days_7',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
    ]
